swagger: "2.0"
info:
  description: "An API that allows a user to get a parking rate for a time span."
  version: "1.0.0"
  title: "Rate API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/"
tags:
- name: "metrics"
  description: "Report of cumulative performance metrics for 'rate' API endpoints"
- name: "ping"
  description: "Status-check endpoint to verify service is available"
- name: "rate"
  description: "Parking rate for a time span"
schemes:
- "http"
paths:
  /metrics:
    get:
      tags:
      - "metrics"
      operationId: "getMetrics"
      produces:
      - "application/json"
      responses:
        200:
          description: "Responds with detailed performance metrics per 'rate' API endpoint."
  /ping:
    get:
      tags:
      - "ping"
      operationId: "getPing"
      produces:
      - "text/plain;charset=iso-8859-1"
      responses:
        200:
          description: "Responds with 'pong\\n' when service available"
  /v1/rate:
    get:
      tags:
      - "rate"
      summary: "Get a parking rate for a time span"
      operationId: "getRateAsDefault"
      produces:
      - "application/json"
      parameters:
      - $ref: '#/components/parameters/startParam'
      - $ref: '#/components/parameters/endParam'
      responses:
        200:
          description: "Parking Rate"
          schema:
            $ref: "#/definitions/Rate"
  /v1/rate.json:
    get:
      tags:
      - "rate"
      summary: "Get a parking rate as JSON"
      operationId: "getRateAsJson"
      produces:
      - "application/json"
      parameters:
      - $ref: '#/components/parameters/startParam'
      - $ref: '#/components/parameters/endParam'
      responses:
        200:
          description: "Parking Rate"
          schema:
            $ref: "#/definitions/Rate"
  /v1/rate.xml:
    get:
      tags:
      - "rate"
      summary: "Get a parking rate as XML"
      operationId: "getRateAsXML"
      produces:
      - "application/xml"
      parameters:
      - $ref: '#/components/parameters/startParam'
      - $ref: '#/components/parameters/endParam'
      responses:
        200:
          description: "Parking Rate"
          schema:
            $ref: "#/definitions/Rate"
  /v1/rate.proto:
    get:
      tags:
      - "rate"
      summary: "Get a parking rate as a Protobuf"
      operationId: "getRateAsProto"
      produces:
      - "application/octet-stream"
      parameters:
      - $ref: '#/components/parameters/startParam'
      - $ref: '#/components/parameters/endParam'
      responses:
        200:
          description: "See 'rate.proto' in justinb99.sampleapi.schema for protobuf schema"
definitions:
  Rate:
    type: "object"
    properties:
      price:
        description: "Price of the parking rate.  Only populated if a rate is available for the submitted time span"
        type: "integer"
        format: "int32"
      status:
        description: "Indicates parking rate is unavailable for submitted time span.  Only populated when a parking rate is unavailable"
        type: "string"
        enum:
        - unavailable
    xml:
      name: "rate"
components:
  parameters:
    startParam:
      name: "start"
      in: "query"
      description: "Start of the time span (inclusive). If 'start' is absent, in an improper format, exceeds 'end', or is on a different date than 'end', the rate will be unavailable.  Regardless of the provided UTC offset, the day of the week will be relative to the time with a UTC offset of 0."
      type: "string"
      format: "date-time"
    endParam:
      name: "end"
      in: "query"
      description: "End of the time span (inclusive). If 'end' is absent, in an improper format, precedes 'start', or is on a different date than 'start', the rate will be unavailable.  Regardless of the provided UTC offset, the day of the week will be relative to the time with a UTC offset of 0."
      type: "string"
      format: "date-time"